### ISSUE TITLE
Ongoing DNS resolution issues in overlay network

### ISSUE THREAD

**Issue by coffenbacher** [tutumcloud/weave-daemon#34] opened 2016-01-04 19:11 UTC
Creating this issue to track a shared issue from https://tutum-community.slack.com/messages/. 

The issue is referring to services by the service/stack DNS name not working.

Discussion starting at https://tutum-community.slack.com/archives/general/p1451930866005043 between @coffenbacher (charlie), @littonchen, @nicj, @brycereynolds.

I don't have a repro at this moment, but we've seen this on and off for a month or more. Probably related to these errors in weave logs, which we see frequently and are also reported by @brycereynolds:

```
Jan 04 10:33:50 weave:  INFO: 2016/01/04 18:33:52.645196 [allocator 1e:2a:1a:c1:76:91] Ignored address 10.7.0.90 claimed by 4f2a741b7c4768b7449c534fec721ae685e77bc62d81b59540c7e7e5ba2d8f59 - not in our universe 
```

**Comment by nicholasjackson** [comment] 2016-01-04 19:55
+1 if you need poke about my transform-dev stack is available

**Comment by fermayo** [comment] 2016-01-05 09:36
The DNS resolution of service names is independent of the overlay network, so it's crucial to differentiate between the hostname not resolving and the connection to the IP not working. What is exactly the error you are having on the application side?

**Comment by kevfromireland** [comment] 2016-01-05 15:25
I am seeing a similar issue. When I start a container, it tries to join the weave network with ip 10.7.0.11 but weave rejects it with the following error message:

```
Ignored address 10.7.0.11 claimed by 99e931ed82f8df3cc51b7af856ad532951039260e2176d633357246850e27c3d - not in our universe
```

That is the id of the container that has just started, but I don't know enough about weave as to why it thinks either that container or ip is outside of something that it should be interested in.

I loved that comment around that piece of code: https://github.com/weaveworks/weave/blob/f039221ec9f8a54e49dd51b9f78c22a5434770de/ipam/claim.go#L35 . I do **not** know what I am doing.

We only started experiencing/noticing this issue today upon upgrading to Docker 1.9.1 via Tutum Web UI. The nodes are all BYON, but provisioned in AWS using the tutum ami

**Comment by fermayo** [comment] 2016-01-05 15:35
That is not an error message - it comes from weave's IPAM system that we do not use. We force each container's IP before it runs. In order to troubleshoot, we need to know whether it's a DNS resolution problem or a network-related connectivity issue.

**Comment by kevfromireland** [comment] 2016-01-05 15:36
Can you provide pointers on how to diagnose to get you what you need? Happy to do remote session as well

**Comment by kevfromireland** [comment] 2016-01-05 15:37
it seems proper network related connectivity.

I have 2 containers in the same service.
I can't ping between them.

Those two containers are linked to a haproxy in another container. It can ping one (by ip) but not the other

**Comment by fermayo** [comment] 2016-01-05 15:37
The error message from the application that fails to connect to another container should give us a hint on what is actually failing

**Comment by kevfromireland** [comment] 2016-01-05 15:39
HAProxy is the application that reports a linked container as down, and ping from the HAProxy to the reported IP of the container fails

**Comment by coffenbacher** [comment] 2016-01-05 17:57
@fermayo our workaround is usually to use the FQDN. My understanding is that routes the traffic over the standard network instead of Weave.

This is what we usually see from the application side, I'm not sure if it's enough to help:
```
root@container-1:/# ping example-service.example-stack
ping: unknown host
```

What other steps would help in diagnosing?

**Comment by fermayo** [comment] 2016-01-05 18:06
That seems a DNS resolution problem. Is the container based on Alpine Linux by any chance? Can you try pinging `example-service.example-stack.<uuid>.local.tutum.io` where `<uuid>` is the Tutum UUID for `container-1`? (You can check the UUID of the container by looking up the environment variable `$TUTUM_CONTAINER_API_URI`)

**Comment by coffenbacher** [comment] 2016-01-06 20:33
Thanks @fermayo. Next time we have the issue (not sure how to repro at the moment consistently) I will try that.

Also, not our issue since we don't have 30 nodes yet, but another note from tutum-community Slack for others: "It seems you have reached the default maximum number of peers of weave (30) and it's refusing new connections. We [Tutum] can increase this limit (weave should be fine up to 100 nodes),"

**Comment by fermayo** [comment] 2016-01-06 21:21
@coffenbacher we are removing that limit in f0467797d174701e3b93ab84419e4d4a5162c38f

**Comment by aknuds1** [comment] 2016-01-14 10:54
I keep having problems reaching a certain Docker service via a Docker link, the error being that the destination host is unreachable. The error normally goes away, but sometimes I am unable to ping the destination by IP address for hours, from within the container that links to it.

**Comment by dciccale** [comment] 2016-01-15 07:55
I am experiencing the same issue, containers kind of fail to link to each other and I see things like

`MongoError: connect EHOSTUNREACH 10.7.0.2:27017`

my solution is clicking the redeploy button from the linking container multiple times until it works

for example I have

```
api
  ...
  - links: mongo 
mongo:
  ...
```

**Comment by FSerg** [comment] 2016-01-17 15:27
+1

**Comment by revett** [comment] 2016-01-19 10:16
**Note** - This is now being mentioned daily on the community Slack.

**Comment by eafzali** [comment] 2016-01-19 10:42
+1

**Comment by revett** [comment] 2016-01-19 11:10
**Call to Action**

@MaximeHeckel has asked anyone experiencing the issue to run https://github.com/fermayo/tutum-network-tester on their stack and post any results in this issue to help with debugging.

**Comment by aknuds1** [comment] 2016-01-19 13:30
@revett I think this network-tester is a bit poorly thought out, as there should be formulated a method for sifting errors out of it. Right now, it's left to users to figure out on our own how to go about this... Couldn't the service auto-email diagnostics to Tutum instead??

**Comment by nq-ebaratte** [comment] 2016-01-19 13:56
This issue also appears regularly on the nodes (BYON) I am running. 

The earliest symptom occurs when a new container is started: the network interface fails to register. I added the following script in all entrypoints:

    # remove /16 after XXX_IP_ADDRESS
    IP=$(echo ${TUTUM_IP_ADDRESS} | sed s'/\/.*//g')

    # network layer may take a bit of time.
    while ! ifconfig | grep ${IP} > /dev/null; do
        echo "$(date) - Waiting for net interface to register ${IP}"
        sleep 1
    done

Broken containers will loop infinitely, no matter what. Restarting the container does not change anything.

The following steps may (or may not) fix the issue:
 - restart the weave container
 - redeploy the stack
 - restart the tutum-agent service
 - reboot the machine

I also noted that if two nodes running tutum-agent fail to communicate (eg. too aggressive firewall), it may confuse weave and cause it to break for some containers network layers. The oddest part being that some containers are broken while others continue to run fine.

**Comment by revett** [comment] 2016-01-19 14:52
From @kevfromireland on Slack:

> We haven’t seen it break randomly. We have seen it break on redeploy when the ip address assigned to a container makes it unreachable from other containers. It looks as though it is assigned an IP but not actually connected to the virtual switch in some way.

**Comment by irony** [comment] 2016-01-31 15:50
We have had this problem for a while. It seems to be only on our local nodes. I tried to install the network-tester in our stack and it can't find any problems while the node-js node can't access the elasticsearch service. 

```
network-tester-2 | 2016-01-31T15:48:25.169994472Z Sun Jan 31 15:48:25 2016: network-tester-2 on /api/v1/node/38d8d92b-xxxxxxxx-a5e6-669369ac3c3b/ is reachable
network-tester-2 | 2016-01-31T15:48:25.169998672Z Sun Jan 31 15:48:25 2016: network-tester-3 on /api/v1/node/85c74d8e-xxxxxxxx-c6c4b75/ is reachable
network-tester-2 | 2016-01-31T15:48:31.735106802Z Sun Jan 31 15:48:31 2016: Trying to contact: 10.7.0.50 10.7.0.63 10.7.0.64
network-tester-2 | 2016-01-31T15:48:31.735138202Z Sun Jan 31 15:48:31 2016: network-tester-1 on /api/v1/node/e1db840d-xxxxxxxx-8e0bb356/ is reachable
network-tester-2 | 2016-01-31T15:48:31.735144002Z Sun Jan 31 15:48:31 2016: network-tester-2 on /api/v1/node/38d8d92b-xxxxxxxx-a5e6-669369ac3c3b/ is reachable
network-tester-2 | 2016-01-31T15:48:31.735149202Z Sun Jan 31 15:48:31 2016: network-tester-3 on /api/v1/node/85c74d8e-xxxxxxxx-c6c4b75/ is reachable
network-tester-1 | 2016-01-31T15:48:34.936460951Z Sun Jan 31 15:48:34 2016: Trying to contact: 10.7.0.50 10.7.0.63 10.7.0.64
network-tester-1 | 2016-01-31T15:48:34.936492851Z Sun Jan 31 15:48:34 2016: network-tester-1 on /api/v1/node/e1db840d-xxxxxxxx-8e0bb356/ is reachable
network-tester-1 | 2016-01-31T15:48:34.936500751Z Sun Jan 31 15:48:34 2016: network-tester-2 on /api/v1/node/38d8d92b-xxxxxxxx-a5e6-669369ac3c3b/ is reachable
network-tester-1 | 2016-01-31T15:48:34.936505651Z Sun Jan 31 15:48:34 2016: network-tester-3 on /api/v1/node/85c74d8e-xxxxxxxx-c6c4b75/ is reachable
network-tester-3 | 2016-01-31T15:48:35.029062208Z Sun Jan 31 15:48:35 2016: Trying to contact: 10.7.0.50 10.7.0.63 10.7.0.64
network-tester-3 | 2016-01-31T15:48:35.029101608Z Sun Jan 31 15:48:35 2016: network-tester-1 on /api/v1/node/e1db840d-xxxxxxxx-8e0bb356/ is reachable
network-tester-3 | 2016-01-31T15:48:35.029108508Z Sun Jan 31 15:48:35 2016: network-tester-2 on /api/v1/node/38d8d92b-xxxxxxxx-a5e6-669369ac3c3b/ is reachable
network-tester-3 | 2016-01-31T15:48:35.029113208Z Sun Jan 31 15:48:35 2016: network-tester-3 on /api/v1/node/85c74d8e-xxxxxxxx-c6c4b75/ is reachable
network-tester-2 | 2016-01-31T15:48:38.172853039Z Sun Jan 31 15:48:38 2016: Trying to contact: 10.7.0.50 10.7.0.63 10.7.0.64
network-tester-2 | 2016-01-31T15:48:38.172888139Z Sun Jan 31 15:48:38 2016: network-tester-1 on /api/v1/node/e1db840d-xxxxxxxx-8e0bb356/ is reachable
network-tester-2 | 2016-01-31T15:48:38.172895239Z Sun Jan 31 15:48:38 2016: network-tester-2 on /api/v1/node/38d8d92b-xxxxxxxx-a5e6-669369ac3c3b/ is reachable
network-tester-2 | 2016-01-31T15:48:38.172900039Z Sun Jan 31 15:48:38 2016: network-tester-3 on /api/v1/node/85c74d8e-xxxxxxxx-c6c4b75/ is reachable
network-tester-1 | 2016-01-31T15:48:41.485249781Z Sun Jan 31 15:48:41 2016: Trying to contact: 10.7.0.50 10.7.0.63 10.7.0.64
network-tester-1 | 2016-01-31T15:48:41.485290981Z Sun Jan 31 15:48:41 2016: network-tester-1 on /api/v1/node/e1db840d-xxxxxxxx-8e0bb356/ is reachable
network-tester-1 | 2016-01-31T15:48:41.485298081Z Sun Jan 31 15:48:41 2016: network-tester-2 on /api/v1/node/38d8d92b-xxxxxxxx-a5e6-669369ac3c3b/ is reachable
network-tester-1 | 2016-01-31T15:48:41.485302781Z Sun Jan 31 15:48:41 2016: network-tester-3 on /api/v1/node/85c74d8e-xxxxxxxx-c6c4b75/ is reachable
network-tester-3 | 2016-01-31T15:48:41.490977361Z Sun Jan 31 15:48:41 2016: Trying to contact: 10.7.0.50 10.7.0.63 10.7.0.64
network-tester-3 | 2016-01-31T15:48:41.491017761Z Sun Jan 31 15:48:41 2016: network-tester-1 on /api/v1/node/e1db840d-xxxxxxxx-8e0bb356/ is reachable
network-tester-3 | 2016-01-31T15:48:41.491024861Z Sun Jan 31 15:48:41 2016: network-tester-2 on /api/v1/node/38d8d92b-xxxxxxxx-a5e6-669369ac3c3b/ is reachable
network-tester-3 | 2016-01-31T15:48:41.491030161Z Sun Jan 31 15:48:41 2016: network-tester-3 on /api/v1/node/85c74d8e-xxxxxxxx-c6c4b75/ is reachable
network-tester-2 | 2016-01-31T15:48:44.685673656Z Sun Jan 31 15:48:44 2016: Trying to contact: 10.7.0.50 10.7.0.63 10.7.0.64
network-tester-2 | 2016-01-31T15:48:44.685723056Z Sun Jan 31 15:48:44 2016: network-tester-1 on /api/v1/node/e1db840d-xxxxxxxx-8e0bb356/ is reachable
network-tester-2 | 2016-01-31T15:48:44.685730756Z Sun Jan 31 15:48:44 2016: network-tester-2 on /api/v1/node/38d8d92b-xxxxxxxx-a5e6-669369ac3c3b/ is reachable
network-tester-2 | 2016-01-31T15:48:44.685749456Z Sun Jan 31 15:48:44 2016: network-tester-3 on /api/v1/node/85c74d8e-xxxxxxxx-c6c4b75/ is reachable
```

**Comment by revett** [comment] 2016-02-02 12:07
From @fermayo on Slack:

> We fixed one of the issues, which was our weave-daemon container going over the memory limit we set, but we are investigating another issue which causes weave-daemon to not detect when some containers start.

> The change has been server side in Tutum, there is no change to weave-daemon source code. And because we don't want to interrupt user's networks, we haven't force pushed the update to everyone - only new nodes will get the update, or we can manually force push the update to nodes if the user wants us to.

**Comment by irony** [comment] 2016-03-16 13:06
This is still a problem. All our nodes suffer from this issue both in Docker Cloud and Tutum. Do you have any updates on the progress?

**Comment by salanki** [comment] 2016-03-18 15:15
I am having intermittent DNS resolutions errors as well on both platforms.

**Comment by fermayo** [comment] 2016-03-18 16:02
This is becoming a catch-all thread for all issues DNS and overlay network related, and most scenarios that we have investigated so far have completely different causes. There are no known issues at the moment in Docker Cloud so we will also need to investigate logs, etc. to get to the root cause.
I suggest you open separate threads for each case detailing the problem (along with application logs) in the [Docker Cloud forums](https://forums.docker.com/c/docker-cloud) so we can better troubleshoot each case. Thanks!

**Closed by fermayo** 2016-03-18 16:02 UTC

**Comment by bstahlhood** [comment] 2016-05-25 16:05
Docker Cloud Forums where all issues go to die and go unanswered...
